# Generated by Django 4.2.3 on 2023-07-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=40)),
                ('address', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('mobile', models.IntegerField(max_length=10)),
                ('image', models.FileField(upload_to='myimages')),
            ],
        ),
    ]
